package org.globalforestwatch.summarystats.annualupdate_minimal

case class AnnualUpdateMinimalDataGroup(lossYear: Integer,
                                        threshold: Integer,
                                        drivers: String,
                                        primaryForest: Boolean,
                                        wdpa: String,
                                        aze: Boolean,
                                        plantedForests: String,
                                        mangroves1996: Boolean,
                                        mangroves2020: Boolean,
                                        tigerLandscapes: Boolean,
                                        landmark: Boolean,
                                        keyBiodiversityAreas: Boolean,
                                        mining: Boolean,
                                        peatlands: Boolean,
                                        oilPalm: Boolean,
                                        idnForestMoratorium: Boolean,
                                        woodFiber: Boolean,
                                        resourceRights: Boolean,
                                        logging: Boolean,
                                        gainPeriod: String,
                                        intactForestLandscapes2000: Boolean,
                                        landCover: String,
                                        tmlDensity: Int,
                                        naturalForests: String
                                       )
