package org.globalforestwatch.summarystats.annualupdate_minimal

case class AnnualUpdateMinimalDataGroup(lossYear: Integer,
                                        threshold: Integer,
                                        drivers: String,
                                        globalLandCover: String,
                                        primaryForest: Boolean,
                                        wdpa: String,
                                        aze: Boolean,
                                        plantedForests: String,
                                        mangroves1996: Boolean,
                                        mangroves2016: Boolean,
                                        tigerLandscapes: Boolean,
                                        landmark: Boolean,
                                        keyBiodiversityAreas: Boolean,
                                        mining: Boolean,
                                        peatlands: Boolean,
                                        oilPalm: Boolean,
                                        idnForestMoratorium: Boolean,
                                        woodFiber: Boolean,
                                        resourceRights: Boolean,
                                        logging: Boolean,
                                        isGain: Boolean,
                                        forestAge: String,
                                        faoEcozones: String,
                                        intactForestLandscapes2000: Boolean,
                                        intactForestLandscapes2013: Boolean,
                                        intactForestLandscapes2016: Boolean,
                                        intactForestLandscapes2020: Boolean,
                                       )
