package org.globalforestwatch.summarystats.carbonflux

case class CarbonFluxDataGroup(
                               fluxModelExtent: Boolean,
                               removalForestType: String,
                               lossYear: Integer,
                               threshold: Integer,
                               isGain: Boolean,
                               isLoss: Boolean,
                               mangroveBiomassExtent: Boolean,
                               drivers: String,
                               faoEcozones2000: String,
                               landmark: Boolean,
                               wdpa: String,
                               intactForestLandscapes: String,
                               plantationsTypeFluxModel: String,
                               intactPrimaryForest: Boolean,
                               peatlandsExtentFluxModel: Boolean,
                               forestAgeCategory: String,
                               jplTropicsAbovegroundBiomassExtent2000: Boolean,
                               fiaRegionsUsExtent: String,
                               braBiomes: String,
                               riverBasins: String,
                               primaryForest: Boolean,
                               isLossLegalAmazon: Boolean,
                               prodesLegalAmazonExtent2000: Boolean,
                               tropicLatitudeExtent: Boolean,
                               isBurnLoss: Boolean,
                               grossEmissionsNodeCodes: String
                              )