package org.globalforestwatch.summarystats.carbonflux

case class CarbonFluxDataGroup(
                               fluxModelExtent: Boolean,
                               mangroveBiomassExtent: Boolean,
                               removalForestType: String,
                               drivers: String,
                               faoEcozones2000: String,
                               wdpa: String,
                               landmark: Boolean,
                               intactForestLandscapes2000: Boolean,
                               plantationsTypeFluxModel: String,
                               intactPrimaryForest: Boolean,
                               peatlands: Boolean,
                               forestAgeCategory: String,
                               jplTropicsAbovegroundBiomassExtent2000: Boolean,
                               fiaRegionsUsExtent: String,
                               brazilBiomes: String,
                               riverBasins: String,
                               primaryForest: Boolean,
                               isLossLegalAmazon: Boolean,
                               prodesLegalAmazonExtent2000: Boolean,
                               tropicLatitudeExtent: Boolean,
                               treeCoverLossFromFires: Boolean,
                               grossEmissionsNodeCodes: String,
                               lossYear: Integer,
                               threshold: Integer,
                               isGain: Boolean,
                               isLoss: Boolean,
                               plantationsPre2000: Boolean
                              )