addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.4")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")
addSbtPlugin("net.pishen" % "sbt-lighter" % "1.2.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.8.1")